app.greeting=Hello
micronaut.application.name=codelessapp
micronaut.server.host=0.0.0.0
micronaut.server.port=8080
micronaut.metrics.enabled=true
micronaut.metrics.export.prometheus.descriptions=true
micronaut.metrics.export.prometheus.enabled=true
micronaut.metrics.export.prometheus.step=PT1M
endpoints.all.enabled=true
endpoints.all.sensitive=false
endpoints.health.enabled=true
endpoints.health.sensitive=false
endpoints.metrics.enabled=true
endpoints.metrics.sensitive=false
endpoints.prometheus.enabled=true
endpoints.prometheus.sensitive=false
